name: image_compressor
description: A Flutter plugin for image compression using native code with FFI.
version: 0.0.1
homepage: https://github.com/Mairramer/image_compressor
repository: https://github.com/Mairramer/image_compressor
issue_tracker: https://github.com/Mairramer/image_compressor/issues
license: BSD-3-Clause

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true